### ISSUE TITLE
Wrong index when assigning "sdr_bass" value

### ISSUE THREAD

**Issue by yoyolicoris** [AIcrowd/music-demixing-challenge-starter-kit#1]
https://github.com/AIcrowd/music-demixing-challenge-starter-kit/blob/7802a7d5de37cddccf842e29603b47b03b2f4e47/evaluator/music_demixing.py#L104

Should be replaced by

```python
scores[music_name]["sdr_bass"] = song_score[0] 
```

**Comment by skbly7** [comment]
Hi @yoyololicon, thanks for pointing it out. 💯
