### ISSUE TITLE
Error cloning repo

### ISSUE THREAD

**Issue by easablade** [AIcrowd/music-demixing-challenge-starter-kit#9]
Hi 

When I try to clone the repo, I get an error when it gets to the data/test/Mu - Too Bright/bass.wav file 

fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0xca0b0]

I have already seen the posts that suggest trying git lfs pull, which I have tried without joy.  See below:

fatal error: still in list

runtime stack:
runtime.throw(0x495d50, 0xd)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.mHeap_AllocSpanLocked(0x6b0ea0, 0x80, 0xc820110000)
	/usr/local/go/src/runtime/mheap.go:590 +0x40c
runtime.mHeap_Alloc_m(0x6b0ea0, 0x80, 0x700100000000, 0xc81fff77ff)
	/usr/local/go/src/runtime/mheap.go:425 +0x1ac
runtime.mHeap_Alloc.func1()
	/usr/local/go/src/runtime/mheap.go:484 +0x41
runtime.systemstack(0x700008dc6e88)
	/usr/local/go/src/runtime/asm_amd64.s:278 +0xab
runtime.mHeap_Alloc(0x6b0ea0, 0x80, 0x10100000000, 0xc82001d220)
	/usr/local/go/src/runtime/mheap.go:485 +0x63
runtime.largeAlloc(0x100000, 0xc800000001, 0x1)
	/usr/local/go/src/runtime/malloc.go:745 +0xb3
runtime.mallocgc.func3()
	/usr/local/go/src/runtime/malloc.go:634 +0x33
runtime.systemstack(0xc820021500)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:674

Git version is 2.31.1 on macOS 10.15.7.

Any help would be much appreciated.

Cheers

Matt

**Comment by skbly7** [comment]
@easablade, it potentially looks like an issue in `git` or `git lfs` installation on your system.

1. I will suggest you to try cloning any random repository and check if it is working fine.
2. Plus, given the error says `mHeap_AllocSpanLocked`, `runtime/malloc.go`, etc point that you may not enough RAM  in your system or it is unable to allocate. Probably restart the machine once if you don't have enough RAM?
3. Upgrade/Reinstall your `git` from `brew` or your whichever way you manage your dependencies.

**Comment by easablade** [comment]
@skbly7 

Awesome, thanks for that - it appears to have been a memory issue.  Restarted machine, cloned absolutely fine.

Cheers

Matt
